Post: new features
rero/sonar.ch pull request #9
Opened 2021-07-07 12:10 UTC by pronguen

2021-07-08 08:54 UTC, iGormilhit approved these changes

2021-07-10 14:15 UTC, mmo requested changes

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +It's been some time since the last update about the SONAR features. The main ones are: research projects, custom collections, persistent identifiers (ARK), custom local fields and Open Access button.
```suggestion
It's been some time since the last update about SONAR's new features. The main ones are: research project management, custom collections, persistent identifier assignment (ARK), custom local fields and an Open Access filter. Let's take a look at these new features in detail and in pictures.
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +## Research projects
```suggestion
## Research project management
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +The promotion of research projects is becoming increasingly important in the age of open science. SONAR enables now to:
```suggestion
The promotion of research projects is becoming increasingly important in the age of open science. For that reason, research projects are now full-fledged entities in SONAR, with their own metadata and deposit workflow. It now enables to:
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +    * either by the research who creates the deposit or by the librarian/administrator who directly enter the document in the database
```suggestion
    * either by the researcher who creates the deposit or by the librarian/administrator who directly enters the document in the database
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +	* it is possible to link to more than one project
```suggestion
	* it is possible to link a document to more than one project
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +	* Search of projects (only in the professional interface)
```suggestion
* Browse the public and professional interfaces by research projects, using:
	* the *Research projects* link in the document detailed view
	* the project detailed view, which includes a list of linked publications
	* the project search feature (currently available in the professional interface only)
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +
```suggestion
Soon, it will also be possible to use a submission and validation workflow for research projects, as is the case for publications.
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +* the configuration is at your fingertips from the administration interface
```suggestion
* each collection has a dedicated URL
* from this view, its is possible to launch a search within the documents of the collection only
* for each collection, a title and a description (in all the languages of the interface) as well as an image can be defined
* the whole configuration is at your fingertips, from the administration interface
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +## Persistent identifiers (ARK)
```suggestion
## Persistent identifier assignment (ARK)
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +* DOIs are often already assigned by the publisher to documents deposited in SONAR, and duplicate DOIs are thus avoided.
```suggestion
* DOIs are often already assigned by the publisher to documents deposited in SONAR, and having multiple DOIs for the same document can create confusion.
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +## Open Access button
```suggestion
## Open Access filter
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +A button now enable to filter in one click the documents that are Open Access.
```suggestion
A switch button now enables to filter the search results to documents that are Open Access.
```

2021-07-10 14:15 UTC, mmo commented on content/post/what-s-new-on-the-sonar-portal.md
> +The main feature we are working one consists in the subdivisions. This will enable an institution to configure departments and to assign submitters and moderators to them.
```suggestion
One of the main features we are working on is *subdivisions*. They enable an institution to define faculties (or departments, sections...) and to assign submitters and moderators to them.
```

2021-07-20 10:51 UTC, pronguen commented on content/post/what-s-new-on-the-sonar-portal.md
> +{{< figure src="/images/open_access_button.jpg" caption="Open Access button" alt="Screenshot of the button in the interface" width="100%" >}}
```suggestion
{{< figure src="/images/open_access_button.jpg" caption="Open Access filter" alt="Screenshot of the switch button in the interface" width="100%" >}}
```

2021-07-20 10:53 UTC, pronguen commented on content/post/what-s-new-on-the-sonar-portal.md
> +date: 2021-07-10T12:00:00+02:00
```suggestion
date: 2021-07-20T11:00:00+02:00
```

2021-07-20 15:26 UTC, merged